Release version 1.9.0
Shortlog of commits since last release:

    Elyézer Rezende (1):
          Add Betelgeuse Checks workflow

    Lukas Pramuk (2):
          Fix AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
          Add Python 3.9 compatibility